### ISSUE TITLE
Not sure how to orchestrate a more complex extension using external Go repo

### ISSUE THREAD

**Issue by kesmit13** [asottile/setuptools-golang-examples#22]
I have a more complex extension I'm trying to write that has a fair amount of Python code and a Python C extension that wraps a library written in Go.  The Python code and the Python C extension are in one repo, and the Go code is outside of that.  I'm trying to figure out if it's possible to somehow merge the C extension code (c and h files) with the code from the Go library into one directory before building.

It's kind of an odd thing to do, but the purpose of the code in the Go repo is to build a c-shared library that can be used on its own.  I'm just wrapping that C API in a Python module.

**Comment by asottile** [comment]
Yeah that should work fine, you can (for instance) import the go code in a small go module and build that into a C extension

Here's an example where I did that: https://github.com/asottile/dockerfile/blob/master/pylib/main.go

**Comment by kesmit13** [comment]
I'm not sure I see the parallel in that project.  I'm not actually importing anything from the external Go project, I'm merely building a Python extension that includes the exported C functions from that Go project.  The Go project really looks more like a C API from the perspective of my Python extension.  What I'm doing now is dropping my Python C extension file into the same directory as the Go project, then pointing setup.py to that directory.  It works, but it's just a workaround until I can figure out a way to not have to modify the Go project with my Python C extension file.

**Comment by asottile** [comment]
ah so you're essentially building a normal C extension (against a C shared object which happens to be built by go), and then you'll want to keep that in your deployed bundle and use rpath to link probably?

**Comment by kesmit13** [comment]
Sort of.  I was trying to skip the step of building the extra shared library and just build everything in one step since it all gets compiled into a single Python extension.  But maybe I'll end up with two files 1) the Python extension and 2) the Go-based C shared library.

**Comment by asottile** [comment]
it might be possible to have an extension with multiple files as the entry, it's been a while since I looked at how this works so I'd have to check that :thinking:

**Comment by kesmit13** [comment]
What I'm kind of thinking is something like this for Extension, but I don't know if that really fits the current model well enough.
```
Extension('_myext', ['github.com/user/project', 'src/myext.c', 'src/myext.h'])
```
Where it would `go get` the source of the project and drop the other files into it before building.  I'm not sure how this would mesh with `build_golang` though.  I might try to patch the code today and see if I can make this work while still keeping it working the old way.

**Comment by kesmit13** [comment]
Here's an idea that might work.  `Extension` could contain a source file that is the primary extension like it does now, but additional items could contain git repos.  The git repos would be compiled with `-buildmode=c-archive`.  The resulting archives from those builds would be added to the link flags.  Still mostly thinking out loud and trying to keep the usage general enough that it solves more than just my immediate problem.

**Comment by kesmit13** [comment]
Well, that almost worked, but there's a fatal flaw.  Every archive that gets created by `go build` contains the Go runtime functions, so they get multiply defined.  Back to the drawing board...

**Comment by kesmit13** [comment]
Since my Go code is really being compiled to a C shared library which is then linked into a C-based extension, I think my situation is too different from what you are trying to do in this project.  I'm going to close the issue.  I think the right thing to do would be to write a build ext command just for my purpose in my setup.py

**Comment by asottile** [comment]
sounds good -- thanks for the issue nonetheless!
